name: villaluna_advmobprog
description: "Flutter Lab Activity 2 project by Villaluna"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  flutter_dotenv: ^5.2.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/NU_shield.svg
    - assets/images/nubdexchange_logo.png
    - assets/images/flutter.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
